# continue_training:
data:
  trainset: /data3/easton/data/HKUST/HKUST_80_new/train/hkust_train.json
  devset: /data3/easton/data/HKUST/HKUST_80_new/dev/hkust_dev.json
  vocab_path: /data3/easton/data/HKUST/HKUST_80_new/vocab.char
  maxlen: 200
  fetchworker_num: 2
model:
  type: Conv_CTC
  add_eos: False
  add_blk: True
  signal:
    feature_type: offline
    spec_aug:
        freq_mask_num: 2
        freq_mask_width: 27
        time_mask_num: 2
        time_mask_width: 40
  encoder:
    type: Transformer
    sub:
      type: ConvV2
      layer_num: 2
    input_dim: 80
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    activation: "glu"
    num_layers: 6
    dropout_rate: 0.1
  decoder:
    vocab_size: -1
training:
    label_type: tokens
    batch_frames: 1000
    multi_gpu: False
    exp_dir: exp/ctc
    print_inteval: 1
    num_epoch: 80
    accumulate_grad_batch: 8
    init_lr: 1.0
    optimtype: adam
    grad_max_norm: 50.
    label_smooth: 0.1
    num_last_ckpt_keep: 1
    lr_scheduler:
        type: warmup_transformer
        warmup_step: 10000
        d_model: 512
