continue_training:
data:
  trainset: /Users/easton/Projects/OpenASR_BaiYe/egs/aishell1_diy/data/test_ark_small.json
  devset: /Users/easton/Projects/OpenASR_BaiYe/egs/aishell1_diy/data/test_ark_small.json
  vocab_path: /Users/easton/Projects/OpenASR_BaiYe/egs/aishell1/data/aishell1_train_chars.txt
  maxlen: 99
  fetchworker_num: 1
model:
  type: conv-transformer
  add_eos: False
  add_blk: False
  signal:
    feature_type: offline
    spec_aug:
        freq_mask_num: 2
        freq_mask_width: 27
        time_mask_num: 2
        time_mask_width: 40
  encoder:
    type: Transformer
    sub:
      type: ConvV2
      layer_num: 2
    input_dim: 80
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    activation: "glu"
    num_layers: 2
    dropout_rate: 0.1
  decoder:
    type: TransformerDecoder
    vocab_size: -1 # derived by tokenizer
    d_model: 512
    nhead: 8
    num_layers: 2
    encoder_dim: 512
    dim_feedforward: 2048
    activation: "glu"
    dropout_rate: 0.1
training:
    label_type: tokens
    batch_frames: 600
    multi_gpu: False
    exp_dir: exp/base
    print_inteval: 10
    num_epoch: 80
    accumulate_grad_batch: 2
    init_lr: 1.0
    optimtype: adam
    grad_max_norm: 50.
    label_smooth: 0.1
    num_last_ckpt_keep: 1
    lr_scheduler:
        type: "warmup_transformer"
        warmup_step: 16000
        d_model: 512
